server:
  port: 9001

spring:
  application:
    name: cloud-order-server
eureka:
  client:
    #    表示是否将自己注册进eureka server  默认位true
    register-with-eureka: true
    #    表示是否从eureka server抓取已有的注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
